version: "3.9"

volumes:
  es_data:
    driver: local

networks:
  elasticnetwork:
    name: elasticnetwork
    driver: bridge

services:
  node:
    container_name: node
    restart: always
    build: .
    command: nodemon index.js
    ports:
      - 8090:8090
    volumes:
      - .:/app
    depends_on:
      - elasticsearch
    environment:
      NODE_ENV: development
    networks:
      - elasticnetwork

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elasticnetwork

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.0
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticnetwork
