version: "3.9"

volumes:
  es_data:
    driver: local

networks:
  elasticnetwork:
    name: elasticnetwork
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    restart: always
    hostname: rabbitmq_host
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - elasticnetwork 
  
  api:
    container_name: api
    restart: always
    build: ./api
    command: nodemon index.js
    ports:
      - 8090:8090
    volumes:
      - ./api:/app/api
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      NODE_ENV: development
    networks:
      - elasticnetwork

  consume-server:
    container_name: consume-server
    restart: always
    build: ./consume-server
    command: nodemon index.js
    ports:
      - 8091:8091
    volumes:
      - ./consume-server:/app/consume-server
    depends_on:
      - rabbitmq
      - elasticsearch
    environment:
      NODE_ENV: development
    networks:
      - elasticnetwork

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elasticnetwork

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.8.0
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elasticnetwork
